In [3]:
import read_data
import ghaussian_method
import numpy as np
import sys

In [4]:
a = read_data.read_file_matrix("example.txt")

In [5]:
a

array([[ 0. ,  4. ,  5. ,  0. ,  3. ],
       [ 0. ,  0. ,  4. ,  2. ,  0.5],
       [-4. , -6. ,  0. ,  1. ,  2. ],
       [ 1.4, -2. ,  3. ,  0. ,  8.9]])

In [6]:
ghaussian_method.transform_to_triangular_matrix(a, "column")

In [7]:
ghaussian_method.comp_determinant(a)

237.6

In [8]:
a

array([[-4.        , -6.        ,  0.        ,  1.        ,  2.        ],
       [ 0.        , -4.1       ,  3.        ,  0.35      ,  9.6       ],
       [ 0.        ,  0.        ,  7.92682927,  0.34146341, 12.36585366],
       [ 0.        ,  0.        ,  0.        ,  1.82769231, -5.74      ]])

In [9]:
ghaussian_method.comp_back_substitution(a)

-5.74
0.0
1.8276923076923077
[ 0.          0.          0.         -3.14057239]
12.365853658536587
-1.0723905723905724
7.926829268292684
[ 0.          0.          1.6952862  -3.14057239]
9.6
3.986658249158249
-4.1
[ 0.         -1.36910774  1.6952862  -3.14057239]
2.0
5.074074074074074
-4.0
[ 0.76851852 -1.36910774  1.6952862  -3.14057239]
